ADD: 新增linux 的exit code lab
labex-labs/labex-trial pull request #5
Opened 2022-12-04 07:52 UTC by matrixm-code

# PR Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] The lab/challenge structure is correct.
- [ ] The format of the lab/challenge is correct.
- [ ] I pledge that I did not plagiarize and I did not copy the solution from other sources.

See more details in [Contributing Guidelines](https://labex.gitbook.io/contributing-guidelines/).

2022-12-04 08:05 UTC, huhuhang requested changes
好像是我们提供的模板内容？

2022-12-05 02:20 UTC, matrixm-code commented
都有哪些模版呀？ 没找到相关内容也 @huhuhang

2022-12-05 03:07 UTC, huhuhang commented
> 都有哪些模版呀？ 没找到相关内容也 @huhuhang

https://github.com/huhuhang/labex-trial/tree/master/linux/lab-basic-operation

这几个都是模板 lab，其他作者提交的也可以看一下。你提交的内容和这个非常接近，确认一下是不是提交错了呢？

2022-12-05 07:31 UTC, matrixm-code commented
啊~ 。 刚发现是因为 vscode 没自动保存，保留的是之前的模版  ~_~.  已经重新提交。

2022-12-07 07:39 UTC, mercury7720 commented
这里的内容有点超纲了哈，还涉及到了 Shell，不太符合我们的初级的定位。如果是要讲到检查命令执行状态建议在一个其他的命令 step 里插入，就简单提一下 0 是成功，1 是失败即可，不建议作为单独内容。如有可能，Shell 的特殊变量 `$#`、`$?`、`$*`、`$$` 等在后续进阶一些的内容里统一讲解比较好。

2022-12-15 01:54 UTC, closed without merging