试写python的数据结构部分
labex-labs/labex-trial pull request #6
Opened 2022-12-06 16:21 UTC by AyoungYa

# PR Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

- [ ] The lab/challenge structure is correct.
- [ ] The format of the lab/challenge is correct.
- [ ] I pledge that I did not plagiarize and I did not copy the solution from other sources.

See more details in [Contributing Guidelines](https://labex.gitbook.io/contributing-guidelines/).

2022-12-07 07:20 UTC, huhuhang requested changes
一些已知问题。请注意浏览 master 分支上的内容，和其他 PR，规避已知问题。

2022-12-07 07:20 UTC, huhuhang commented on python/lab-data-structures/intro.md
> +In this lab, we'll learn data structures in python, main contents
python 等专有名词，请使用官方大小写。

2022-12-07 07:20 UTC, huhuhang commented on python/lab-data-structures/step1.md
> +# Index
突然由变成一级标题？标题的层级要厘清。

2022-12-09 02:38 UTC, huhuhang commented
我对部分格式进行了修改，请看记录。

此外，步骤需要添加 verify 脚本，我添加了一个示例。

在这个示例中，首先通过我们提供的一个启动脚本，便于实时获取到 Python Shell 的历史记录。https://github.com/labex-labs/common-scripts/tree/master/python-shell-history

然后就可以在 verify 脚本中查询关键词，以确认用户进行了步骤相关操作。

值得注意的是，在 lab 中的匹配不要大段落全文匹配，允许用户适当灵活发挥，以避免用户被 verify 脚本卡住。提示要准确。

2022-12-11 04:53 UTC, AyoungYa commented on python/lab-data-structures/intro.md
> +In this lab, we'll learn data structures in python, main contents
done

2022-12-11 04:54 UTC, AyoungYa commented on python/lab-data-structures/step1.md
> +# Index
已经改为2级标题

2022-12-11 09:47 UTC, huhuhang commented
没有提交成功？最后一个 commit 还停留在我提交的。

![CleanShot 2022-12-11 at 17 47 24](https://user-images.githubusercontent.com/5147530/206896841-e66eb2ea-9c1f-4de0-814f-dad1d0d10639.png)

2022-12-11 11:20 UTC, AyoungYa commented
已经提交修改

2022-12-14 05:25 UTC, huhuhang approved these changes

2022-12-14 05:25 UTC, merged

2023-04-17 04:48 UTC, huhuhang commented
Hi, @AyoungYa 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。